### PR TITLE
Options builder support (#672)

### PR DESCRIPTION
**Pull request by AndrewTriesToCode**
* Implement support for OptionsBuilder

* Reverted changes to TenantConfigureNamedOptions

* Restored commented test

* Removed dependencies

---------

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
rebasing

**Comment by AndrewTriesToCode** [comment]
Ok @goldsam sorry for the delay. I'm active on this again. Thanks for the head start. I am going to make a few design changes but I really like the options wrapper -- I think I won't need a custom options factory anymore with this. I also like your Options Builder related code. I will probably slightly reformat some method names.

I am going to deprecate `WithPerTenantOptions` on `MultiTenantBuilder` in favor of `ConfigurePerTenant` variants directly on `IServiceCollection`. I hope to get this out soon. I won't be able to work on it really over Thanksgiving week so I will try to get it there this week. That will make Finbuckle Options very aligned with the vanilla ones in terms of naming and use for regular options and options builder with DI.

Thanks again.

**Comment by goldsam** [comment]
@AndrewTriesToCode Thank you so much! Glad my contribution was welcome.

**Comment by mikecowgill** [comment]
I'm looking forward to switching to the ConfigurePerTenant method. I have a use case that depends on being able to add the options conditionally, outside of the .AddMultiTenant configuration. This PR looks to help achieve that nicely.

**Comment by AndrewTriesToCode** [comment]
Glad to hear it will help you. I’m on vacation this week but will prioritize it shortly. I still need to update the docs to reflect the changes and consider tests.

**Comment by goldsam** [comment]
It looks like you're closing in on the finish line 🥳🎉

**Comment by AndrewTriesToCode** [comment]
Getting there. I apologize for the slow cadence. I’m going to lump in a few other breaking changes and get this out in March.

**Pull request merged**
