### PR TITLE
feat: Added support for named options (#478)

### PR DESCRIPTION
**Pull request by LamarLugli**

### CODE REVIEW

**Comment by LamarLugli** [comment]
I added support for named options using the `WithPerTenantNamedOptions<TOptions>` extension method on the builder.  This will preserve backwards compatibility with users using `WithPerTenantOptions<TOptions>`.

**Comment by AndrewTriesToCode** [comment]
Thank you very much! 

Do you think you can add in some unit tests to confirm that the right named options are impacted and no other named or unnamed options are?

Can you update the docs to mention that named options are supported with this method?

I'll try to review this quickly.

**Comment by LamarLugli** [comment]
I would be happy to update the documentation. I'll update the pull request with some new documentation.

`Do you think you can add in some unit tests to confirm that the right named options are impacted and no other named or unnamed options are?` Are you asking about different classes of options to make sure there is no crossover, or configuring two different names of the same class?  My existing tests already cover the latter.

**Comment by AndrewTriesToCode** [comment]
Ah perfect -- I didn't see your tests and first and I see now you did update the docs. Thanks again! I will get this out in a release ASAP.

**Comment by AndrewTriesToCode** [comment]
Note to self -- prioritize for this week.

**Comment by AndrewTriesToCode** [comment]
@LamarLugli I made some edits and I want to see if you agree. I also updated the docs -- if you agree with my changes I'll go ahead and put out a new release.

1.  I reworked your named options class so that it works like this:
```cs
services.AddMultiTenant<TenantInfo>()...
    .WithPerTenantNamedOptions<MyOptions>(name, (options, tenantInfo) =>
    {
        // only update options named "someOptionsName"
        options.MyOption1 = (int)tenantInfo.Items["someValue"];
        options.MyOption2 = (int)tenantInfo.Items["anotherValue"];
    });
```
The difference is the name isn't part of the delegate and the delegate only gets called if the name is correct via the options factory (so no need to check if the name matches). This is how .NET does it and I wanted to match it as closely as possible.

2. I obsoleted the unnamed options types and now `WithPerTenantOptions` simply calls `WithPerTenantNamedOptions` with a null name -- this means it works just like before but piggy backs on your implementation.

**Review by AndrewTriesToCode — APPROVED** [review]
I made some changes -- see my comment.

**Comment by LamarLugli** [comment]
This looks great.  Thanks for making this even better.

**Pull request merged**
