### PR TITLE
Added non-generic version of IsMultiTenant extension method.

### PR DESCRIPTION
**Pull request by Andrew-Oliveira**
I required a non-generic version of this method to dynamically mark entities as tenants. I figured this would count as a "small change", especially since I just copied the existing method and tweaked it a little, so apologies if you find this falls outside your contributing guidelines.

Example in OnModelCreating method:
`foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())
{
   modelBuilder.Entity(entityType.Name).IsMultiTenant();
}`

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/Finbuckle/Finbuckle.MultiTenant?pullRequest=412) <br/>All CLA requirements met.

**Comment by AndrewTriesToCode** [comment]
@Andrew-Oliveira thank you for the contribution.
I agree the generic version is better -- I used to have it like that in the library, changed it, and now I want it back too!

I am testing some GitHub action stuff so I am going to close and reopen this PR -- don't worry though I intend to merge after I review.

**Comment by AndrewTriesToCode** [comment]
@Andrew-Oliveira I'm having a hard time getting the unit tests to pass. With a non-generic version of `IsMultiTenant` the generic one isn't needed since `EntityTypeBuilder<T>` inherits from `EntityTypeBuilder`... but even removing the generic one I can't get this to work.

I'm going to leave the PR open -- I might merge in PR #372 soon which will also solve the problem for you.

**Comment by AndrewTriesToCode** [comment]
PR #372 will include a non-generic version os `IsMultiTenant` closing this PR out to keep things managable

**Pull request closed without merging**
