### PR TITLE
Adding support for more advanced IdentityDbContext customizations

### PR DESCRIPTION
**Pull request by Cpcrook**
Adding an implementation for MultiTenant IdentityDbContext<TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>

### CODE REVIEW

**Comment by Cpcrook** [comment]
Amended commit with a signed version of the same, hence the dupes + merge.

**Comment by AndrewTriesToCode** [comment]
Closes #44 when merged.
Pending review and potentially adding onto this great work with more forms of the IdentityDbContext.

**Comment by AndrewTriesToCode** [comment]
Hi @Cpcrook I added onto your pull request. This really improves the Identity support--thanks for your help! Since I don't have much unit testing around Identity I want to test this out a bit before merging into Dev.

**Comment by Cpcrook** [comment]
Sounds good @achandlerwhite - I'm going to do a little manual testing (hopefully today) as well.  If I get some unit & integration tests written around the identity stuff in general I'll commit it to this PR branch.

**Comment by Cpcrook** [comment]
I'm going to suggest leaving the use of generic Identity* classes as the generic parameter constraints.  

I'm actually doing a slightly different form of multi-tenancy where I want to leave the Identity* models alone (not adding TenantId to them) and simply switching DB connection strings to a tenant-specific DB containing Identity-related tables for the creation of tenant-specific identities. 

In my case, there is no need to differentiate tenants on a record-by-record basis in the identity tables -- it's handled by the DB connection alone (I'm planning to replicate user records from our IdentityServer4 users table to the tenant DBs, based on tenant claims they get assigned).  I'm mainly using this for the TenantContext connection string injection.

Maybe leave the helper classes in, and just leave the constraints looser (i.e. Identity*<TKey>)?  

Or maybe we split these pieces of functionality into:

* PerRecordMultiTenantIdentityDbContext (existing case)
* PerDbMultiTenantIdentityDbContext (my case, looser type constraints, and without the tenant-enforcement code?)


Just throwing some ideas out there to satisfy both use cases.

**Comment by AndrewTriesToCode** [comment]
@Cpcrook I agree with you--

I intended that the "long-form" class you first committed would have the generic constraints be the normal Identity* classes like you originally did... I think I got carried away with copy/paste. That way someone could specify their own entity types or use the defaults by using the long-form version of the class. I'll make that change later today.

For the shorter variants I prefer to use the derived MultiTenant types as constraints to provide a good default... Identity can get tricky if multiple tenants share *some* of the underlying classes, but not all of them. There is always the 'long-form" variant people can use to have full control.

Also if you are going with a multiple dedicated database approach, the default identity db context works--no need for our classes at all in that case unless you want to build in the option for a shared or hybrid database in the future using the same context.

**Comment by Cpcrook** [comment]
Good point!  Wasn't thinking.  

~~That's a bit cleaner just using tenant-transformed DbContextOptions.~~

Actually, after trying this, it doesn't appear to be hitting the WithPerTenantOptions<DbContextOptions<ApplicationDbContext>>...

**Comment by AndrewTriesToCode** [comment]
Yeah sometimes the aspnetcore or efcore internal code doesn't use options in a straightforward way--they calculate it once and cache them or use an options builder--which is what I think efcore does.

I've only extensively tested per tenant options for use of the app's options or with the aspnetcore authentication options. Do you mind logging an issue about WithPerTenantOptions<DbContextOptions> not working as expected? I will try to take a look at it.

I've been focusing on getting the samples updated (working on an identity sample for this pull request) and overall documentation (which isn't in the repo yet--I plan to add it soon).

**Comment by AndrewTriesToCode** [comment]
Quick update:
I have the sample application working and am cleaning it up to add to the PR. I will then do a final check and merge in.

**Comment by AndrewTriesToCode** [comment]
Fix #49 
Fix #50 
Fix #51 
Fix #46 

Added some fixes and a sample Identity app showing shared database and separate database scenarios.

Doing some more testing and planning to merge soon.

**Comment by AndrewTriesToCode** [comment]
@Cpcrook I'm planning to go ahead and merge in the PR soon. Do you have any further commits to add?

**Pull request merged**
