### PR TITLE
Add a native CosmosDB provider

### PR DESCRIPTION
**Pull request by Valks**
Adds a new datasource provider using ```Microsoft.Azure.Cosmos```

Still some work to do:
- [x] Samples
- [ ] Tests
- [ ] Documentation

That said it works and it would be good to get some feedback on the good and the bad.

As for how to use:

During startup:
```C#
builder.Services.AddMultiTenant<TenantInfo>()
                .WithCosmosDbStore(
                    services => new CosmosClientBuilder(configuration.GetConnectionString("Database"))
                            .WithSerializerOptions(new CosmosSerializationOptions() { PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase })
                            .Build(),
                    (client, services) => ActivatorUtilities.CreateInstance<DbContext>(services, client, "DatabaseName"),
                    context => context.Tenants.Container)
                .WithClaimStrategy("organisationId");
```

```TenantDb``` needs to derive from ```Finbuckle.MultiTenant.CosmosDb.Stores.DatabaseContext``` and implement the abstract class.

As an example:
```C#
public class DbContext : DatabaseContext
    {
        public DatabaseCollection Tenants { get; set; }

        public DbContext(CosmosClient client, string databaseName, ILogger<DbContext> logger)
            : base(client, databaseName, ThroughputProperties.CreateManualThroughput(400), logger)
        {
            Tenants = new DatabaseCollection(nameof(Tenants), $"/{nameof(TenantInfo.Id).ToLower()}", ThroughputProperties.CreateManualThroughput(400));
        }

        public override async Task InitializeAsync(CancellationToken cancellationToken = default)
        {
            var createContainerTasks = new List<Task>();

            createContainerTasks.Add(RegisterContainerAsync(Tenants));

            await Task.WhenAll(createContainerTasks);
        }
    }
```

Then to use the ```DbContext``` just inject it and you'll also have access to the Collections to use elsewhere.

I've used Func<> during startup so you can initialize the CosmosClient, DbContext and select the Container yourself. That way if you've already created a CosmosClient you can retrieve it from services and use it.

I still need to do a little bit of cleanup, with the rework around using Func<> I think the CosmosDbStoreContext can be refined. Anyway, like I said I'm putting this out there for feedback and thoughts, it's still a draft but it works.

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
@Valks 
I'm simplifying the git repo and going with feature branches off the `main` branch going forward. I modified this PR to target main.

**Comment by AndrewTriesToCode** [comment]
Sorry, didn't intend for StaleBot to flag this one

**Comment by AndrewTriesToCode** [comment]
I'm so sorry I've really let time slip. This PR is next up (I think it needs to be in place before the Azure Functions support PR right?).

Is this PR still something you'd like to contribute and if so any further progress on tests and docs?

**Comment by Valks** [comment]
I'm pretty sure I broke the code up so the Azure Functions PR and this one were separate. If anything the Azure Functions PR probably depends on this.

As I said in https://github.com/Finbuckle/Finbuckle.MultiTenant/pull/398 I'm happy to take a look and make sure everything is working.

As for tests and docs I'll take a look at the same time.

**Comment by AndrewTriesToCode** [comment]
This looks pretty good and stands alone from the Azure Functions support. I think a small section could be added to the Stores doc page that gives a short overview and refers to the samples. I think it's also fair to assume that a user would have a working understanding of CosmosDB to make documenting this store simpler.

Is there a good way to unit test against CosmosDB?

**Comment by AndrewTriesToCode** [comment]
Hello, would you help me move this PR forward? I'm not sure how unit tests for this could be handled, but if it is simple enough we can include it without.

**Comment by Valks** [comment]
So first up, sorry life got in the way after I last commented, I should have left an update.

I cannot put a timeline on when I'll be available to look at these commits. It's something I'll get to but not sure when.

To test cosmos DB there's a local emulator that can be used. From a quick google search, it looks like someone has prepared it for GitHub actions: https://github.com/marketplace/actions/azure-cosmos-db-emulator

When I last looked at it I got the feeling that some of the naming and registration could be improved which I started to look at when I wrote the documentation blurb but I didn't complete it.

While it uses standard commands for cosmos DB to prepare itself and work with the database a few unit tests to make sure it can create the container, create the tenant, validate a tenant and filters data to within the tenant (uses the partition key).

**Comment by Valks** [comment]
I did some minor cleanup to remove the .net core 2.0 target so that it builds again.

I started locally looking at putting together some unit tests but it's something that will take me some time to do.

As I said before I cannot commit time at the moment to work on this so I won't make a promise I cannot keep.

The CosmosDb provider is very bare-bones and basically exposes the CosmosDb API commands with the PartitionId pre-filled to the tenant Id. It works and should be reliable, but like EF core it's something that should be tested.

**Comment by AndrewTriesToCode** [comment]
Hi @Valks, I believe this fits into the updated contribution guidelines pretty well. I am starting to actively review and have some incoming feedback -- mainly around simplifying some things.

Thanks again!

**Comment by AndrewTriesToCode** [comment]
I went ahead and rebased the branch on 'main' and added .net 6 as a target. I have a few questions:

1. Do you think we can stipulate that a `CosmosClient` is available via DI to simplify the `WithCosmosDbStore` call?
2. Any chance you can make the sample a .NET 6 project? I'm trying to make that the default going forward.
3. I noticed the `MultiTenantCollection` class -- looks interesting -- basically uses the tenant id as the partition and ensure it is set accordingly right? I didn't see anything in the docs or the samples for it -- did you intent to include it here?

Thanks again!

**Comment by AndrewTriesToCode** [comment]
@Valks first, thanks so much for you contributions. I do plan to add a cosmos db provider but I have one almost ready in which I took a slightly different approach. I'm going to close out this PR since we haven't had any movement on it, but please don't take any offense. I greatly appreciate it and I hope it has worked well for you.

**Comment by Valks** [comment]
Not at all, I've been keeping a note to come back to this just haven't been able to make the time.
I'm glad you have something else in the works, curious to see the results.

**Pull request closed without merging**
