### PR TITLE
Re-implemented WithRemoteAuthentication

### PR DESCRIPTION
**Pull request by Nisden**
Moved the elements that allowed for custom OIDC authentication back into WithRemoteAuthentication, as that resolves the issues I have #369 

I tested in our own solutions, and it works well there.

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
hi @Nisden 

I think you'll also need 

```cs
builder.Services.Replace(ServiceDescriptor.Singleton<IAuthenticationSchemeProvider, MultiTenantAuthenticationSchemeProvider>());
```

to make sure tenants can have different schemes -- otherwise it will always use the schemes from the first user.

Instead of this PR would you find it acceptable if I made `WithRemoteAuthenticationCallbackStrategy` public in the next release so you can just call it directly?

**Comment by Nisden** [comment]
Hi Andrew.

I would find that a shame, as you would also have to make `MultiTenantAuthenticationService` public.

**Comment by AndrewTriesToCode** [comment]
@natelaff 
Take a look at this branch:
https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/refactor/per-tenant-authentication

It has the following changes:
- Added WithPerTenantAuthenticationCore
- Added WithPerTenantAuthenticationConventions
- Exposed WithRemoteAuthenticationCallbackStrategy
- Modified WithPerTenantAuthentication to call the above
- Various fixups

I believe this would support your use case -- you'd just call `WithPerTenantAuthenticationCore` and `WithRemoteAuthenticationCallbackStrategy` and avoid all the convention based stuff. Most people would use `WithPerTenantAuthentication` which internally calls those.

Thoughts?

**Comment by natelaff** [comment]
@AndrewTriesToCode that's a good change. I don't remember why I wanted it-- I think I was going to throw this in my API layer or IS4 project and that just came with too much baggage. 👍

**Comment by AndrewTriesToCode** [comment]
@Nisden I just now realized I meant to reference you above! I'm sorry about that. I'm going to merge in the changes I described above which should allow you to avoid the unneeded functionality in a clean way.

**Comment by AndrewTriesToCode** [comment]
Implemented in #377 
Thanks @Nisden for the discussion and feedback.

**Comment by Nisden** [comment]
@AndrewTriesToCode Thank you for the great library!

**Pull request closed without merging**
