### PR TITLE
[#805] Implemented the Echo Store.

### LINKED ISSUE #805: [Question] MultiTenancy without stores?
Hey @AndrewTriesToCode, I’m relatively new to this library and I’m enjoying it so far, but I have a question: Is it somehow possible to implement MultiTenancy without specifying/implementing any stores?

I’m using Keycloak to specify my tenants (realms). I’ve already implemented the authentication part (custom) and I’m not trying to use ‘WithPerTenantAuthentication’ here. The tenant name/identifier can be retrieved from the token, so that’ll be my strategy. 

As for the TenantInfo, I just need one with the id/identifier set to this claim value, without any additional settings. I don’t really like having to specify all the different tenant names in the config. Hence the question.

So again, is it somehow possible to have a sort of ‘tenant resolver’ that returns a Tenant with the id/identifier set to a value in a token, without having to specify/configure a store?

I hope this makes sense, thanks!

### PR DESCRIPTION
**Pull request by Thijs153**
resolves #805 with an Echo Store that returns a new tenant instance based on the given identifier.

### CODE REVIEW

**Comment by Thijs153** [comment]
@dotnet-policy-service agree

**Comment by AndrewTriesToCode** [comment]
@Thijs153 Looks great! I'm sorry I didn't realize a different PR I merged would cause conflicts. Can you resolve and I will merge ASAP? The conflicts should be very minimal.

**Comment by Thijs153** [comment]
Hey @AndrewTriesToCode, a little late, but I just saw your message. I resolved the conflicts, and I believe it should be good now. Let me know 🙂

**Comment by AndrewTriesToCode** [comment]
Thanks!

**Pull request merged**
