### PR TITLE
feat: .net8.0 LTS release support

### PR DESCRIPTION
**Pull request by paulczy**

### CODE REVIEW

**Comment by paulczy** [comment]
@dotnet-policy-service agree

**Comment by AndrewTriesToCode** [comment]
thanks @paulczy !

**Comment by AndrewTriesToCode** [comment]
@paulczy 
The CI script needs a little work -- the install .NET script doesn't need the matrix since 6 and 7 are installed by default. In theory 8 is too but probably still need to explicitly install it too.

I will make some time tomorrow to make the change if you are not able to get to it. Thanks again.

**Comment by paulczy** [comment]
@AndrewTriesToCode Well, that's what I get for not testing before creating the PR. I tested the CI Workflow action on my repo and got it work by pinning the action runner's SDK to 8.0. I kept the matrix there so you can test other frameworks like you were before. I am assuming the latest dotnet SDK can reliably replicate older versions specified by the framework flag.

**Comment by AndrewTriesToCode** [comment]
Perfect!

**Pull request merged**
