### PR TITLE
remove dependency on NewtonSoft.Json

### PR DESCRIPTION
**Pull request by bobbyangers**
for .NET 5 and 6

Done #504

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
Thanks. I’ll review and merge asap.

**Comment by AndrewTriesToCode** [comment]
Did you run into any issues with the .net 3.1 targets that prevented using system.text.json?

**Comment by bobbyangers** [comment]
@AndrewTriesToCode ;   I ran all the unit tests.   If it's required to add a testing profile for .NET 3.1, let me know.

But since we need to target .NETSTANDARD 2.1;  in that case, Newtonsoft.Json is still used.

**Comment by bobbyangers** [comment]
@AndrewTriesToCode >>  hold off on the approval

I just saw that:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-overview?pivots=dotnet-core-3-1
we can make it work by adding the package explicitely;

**Comment by bobbyangers** [comment]
@AndrewTriesToCode, here, ever more clean !

**Comment by AndrewTriesToCode** [comment]
@bobbyangers thanks, much appreciated!

**Pull request merged**
