### PR TITLE
Tenant not found event

### PR DESCRIPTION
**Pull request by natelaff**
This pull request implements a new Events property to MultiTenantOptions which allows you to hook into an event when the TenantResolver cannot resolve a tenant from the store. This is useful for redirecting to a not found page.

Additionally the AuthenticationService was modified to not challenge if the tenant is null.

Example usage:

```csharp
services.AddMultiTenant<TenantInfo>(config =>
                {         
                    config.Events = new MultiTenantEvents()
                    {
                        OnTenantNotFound = async (context) =>
                        {
                            if (context.Context is HttpContext httpContext)
                            {
                                httpContext.Response.Redirect($"/notfound");
                                await Task.FromResult(0);
                            }
                        }
                    };
                })
```

### CODE REVIEW

**Comment by natelaff** [comment]
Oops. Used my develop as the starting point so it pulled HeaderStrategy back in. If you like where this is headed I can clean all that up and resubmit.

**Comment by AndrewTriesToCode** [comment]
@natelaff Hi, thanks again. I'm going to hold off including this in the upcoming 6.1 release, but this is something I want to add soon. I also plan to include events for after an identifier is found and after a TenantInfo is found.

Feel free to resubmit based on 6.1 or if you are busy I'll reimplement. Cheers.

**Comment by natelaff** [comment]
Sure, I will resubmit. I knew you were getting close to the net50 release and didn't expect to sneak it in there, mostly wanted you to review it. I don't want to step on any toes, just trying to help where I can and this seems like a good addition. But I am also happy to hear any ideas you had for tackling this as it looked like you had it on your radar at one point (returning 404 I think), but this implementation also lets you handle that.

Agreed that another event for tenant resolved as well as which strategy/store resolved it would be good. Maybe those two things are not super necessary to pass back. Having trouble thinking of what I would personally use a TenantFound event for other than custom logging, but I'm sure someone will have a use for it!

**Comment by AndrewTriesToCode** [comment]
@natelaff. Sounds good. One idea for the tenant found event is to pair it with the distributed cache store so it can cache the results of the other primary stores.

**Comment by natelaff** [comment]
@AndrewTriesToCode ah yeah that's a good use case! i hadn't looked at that store yet so i figured you were doing something there already. this would definitely work for that scenario, too.

i am about to reintegrate this into the latest develop branch.

**Pull request closed without merging**
