### PR TITLE
Updated claims strategy to work with multiple authentication schemes

### PR DESCRIPTION
**Pull request by JonasDev17**
I have tested this as a custom strategy and it works. Unfortunately its a breaking change though so it might not be viable as a PR.

### CODE REVIEW

**Comment by JonasDev17** [comment]
@dotnet-policy-service agree

**Comment by JonasDev17** [comment]
Or as you mentioned in #765 changing the the claim strategy to transient or scoped should work too without introducing a breaking change.

**Comment by AndrewTriesToCode** [comment]
Thanks and thanks for the sponsorship!

Based on this PR I’m guessing you found the workaround I alluded to. Cheers!

**Comment by AndrewTriesToCode** [comment]
Just an update will be looking at this for next release.

**Comment by AndrewTriesToCode** [comment]
@JonasDev17 hi there, I didn't realize a different PR would cause a merge conflict with your PR. Would you be able to resolve the conflicts? I will merge it ASAP.

**Comment by AndrewTriesToCode** [comment]
Looking into this and I think instead I will close this PR and address this as a part of moving most strategies to transient scope.

**Pull request closed without merging**
