### PR TITLE
Add Finbuckle.MultiTenant.AspNetCore.OptionsCacheReset

### PR DESCRIPTION
**Pull request by Albert-the-jit**
add `MultiTenantOptionsResetManager `Middleware and `WithPerTenantManagedCacheOptions`
methods for auto reset options cache
related to this [issue ](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/451)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/Finbuckle/Finbuckle.MultiTenant?pullRequest=453) <br/>All CLA requirements met.

**Comment by Albert-the-jit** [comment]
i add a sample and document I hope this helps

**Comment by AndrewTriesToCode** [comment]
Thanks for the samples and documentation. I haven't forgotten about this!

**Comment by AndrewTriesToCode** [comment]
Hi @Azaferany 
Thank you again for your PR. I'm glad you found a good solution for your requirements, and I am impressed by your submission. However, in the interest of maintainability and focus, I'm declining the PR because the use-case is very specific. I encourage you to create your own repo for your contribution, and I will link to it in the official documentation if you would like to share what you have built. I apologize for taking so long to respond and I hope that you still find this library to be helpful. Please let me know if you have any questions and thanks again.

**Pull request closed without merging**
