### PR TITLE
Use semantic logging and reduce string allocations

### PR DESCRIPTION
**Pull request by lahma**
The logging utility caused call sites to always allocate new strings via string formatting even tough debug logging was suppressed on every HTTP call. Now using ILogger directly and defaulting to NullLogger when it's  not available. Using message template place holders so semantic logging works nicely with providers like Serilog.

Added extra check on call sites for debug level so that params array creation won't happen. Also removed GetType from message as it's part of logger name already and more of a configuration issue for logging library to show logger's name.

Had to also update PerTenantAuthenticationSample.csrpoj as it was referring unpublished version 6.1.1 .

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
Thanks @lahma 

I plan to mege in this PR after the next upcoming release.

**Comment by AndrewTriesToCode** [comment]
@lahma  
I'm simplifying the git repo and going with feature branches off the `main` branch going forward. I modified this PR to target main.

**Comment by lahma** [comment]
I've rebased this against latest main.

**Comment by AndrewTriesToCode** [comment]
Thanks @lahma, I expect that this will get merged in the coming month. Have some project news coming soon that will require a signed CLA before we can merge -- I'll keep you posted

**Comment by AndrewTriesToCode** [comment]
@lahma Thanks for being patient with me and for your contribution. This library has recently been accepted into the .NET Foundation and as a part of that process all contributors have to go through a CLA workflow. It works automatically on new PR requests -- would you mind resubmitting this under a new PR?

**Comment by lahma** [comment]
Sure, created #411

**Comment by devalot76** [comment]
> 
> 
> This library has recently been accepted into the .NET Foundation

Wow, this sounds like a very good news! 👍 Can you explain what this exactly means for the project, please?

**Pull request closed without merging**
