### PR TITLE
Add optional parameter to specify the schemeProvider.

### PR DESCRIPTION
**Pull request by Valks**
In Azure Functions setting a default provider breaks the other providers but is a requirement for the tenant strategy to locate the correct ```schemeProvider```.

Apply the handler Principal back to the ```httpContext``` so that other services can access the resolved Claims.

If the user is already authenticated bypass (will throw an exception if called twice).

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
@Valks 
Thanks for being patient with me and for your contribution. This library has recently been accepted into the .NET Foundation and as a part of that process all contributors have to go through a CLA workflow. It works automatically on new PR requests -- but I'm not sure about you draft PRs. Would you mind if we take this one out of draft status to see if the CLA bot workflow kicks in?

**Comment by Valks** [comment]
Doesn't look like it triggered.
I can re-submit the PR's tomorrow if need be.

**Comment by AndrewTriesToCode** [comment]
@Valks 
I think if you can just resubmit one of them we’d be good. It’s a per contributor thing not per PR so one will be good enough.

**Comment by Valks** [comment]
Looks like closing and opening the pull request did the trick.

That said, I've already signed the CLA when contributing to the https://github.com/dotnet/aspnetcore in the past.

**Comment by AndrewTriesToCode** [comment]
Perfect, thanks for jumping through the hoops

**Comment by AndrewTriesToCode** [comment]
@Valks didn't mean for StaleBot to flag this -- still planning to incorporate it, thanks

**Comment by AndrewTriesToCode** [comment]
In reviewing this a few thoughts:

0. Can you point me to some Azure Functions resources that explain the problem this is solving? I'm not too familiar with them yet.

1. I think checking if there is already an authenticated user is ok, but I'm not aware of any use cases -- usually `UseMultiTenant` appears before `UseAuthentication` in an app pipeline -- am I missing something? Also in what situations do you find yourself having 

2. I'm generally wary of setting the `User` principal during the strategy code because principal validation is usually bypassed in this part of the code (cookie tenant is validated against the request tenant, which at this point would always fail because we are in the middle of determining the tenant. This validation is useful for the other tenant strategies to make sure they match the logged in user during the "real" authentication). Since I skip the validation, which may include extra validation for the app, I like the idea of the regular `UseAuthentication` still running later to set the `User` and do the validation there.

    Also, since the scheme handler has already been created it is reused later during the "real" authentication and there is little overhead because the cookie contents were cached from the strategy reading it.

**Comment by Valks** [comment]
So it has been quite a while since I looked at this code.

In my application where I'm using this code, I don't actually call ```UseMultiTenant``` or ```UseAuthentication```. I don't remember if it's because there was a problem (I suspect that the difference in the HTTP pipeline meant it didn't work) or an oversight. It would be worth checking to see if that fixes the main issue where the ```User``` principal wasn't been populated when trying to evaluate the tenant (which lead to this code-change).

That said, there may still be an issue because Azure Functions registers some Auth providers (internally) and when you try to add more it removes those providers. I had to re-add them using Reflection so that Azure could still talk to the service.

As for setting the ```User``` principal, I'm pretty sure I took inspiration from code in the Microsoft Web Identity repository (https://github.com/AzureAD/microsoft-identity-web) which used the same technique. Unfortunately, I don't have notes on where I found the code.

Looking into this made me realise that I didn't add the code to register the default providers back into the Azure Functions pull request.

I'll try and find a moment later this week to look at these pull requests and see if ```UseMultiTenant``` is required and look at adding the code to enable re-registration of the default providers.

**Comment by Valks** [comment]
Ah, wish I looked at the main PR first

```
You don't need to call UseMultiTenant(), it's already done as part of the binding startup.
```

Still, I'll take a look.

**Comment by AndrewTriesToCode** [comment]
Thanks. I think I get what you are saying -- the baked in authentication may get executed before `UseMultiTenant` in the binding startup -- you don't get much control there. In that case user is already set so all good there. If `UseMultiTenant` executes first I'm still where of setting `User` when validation for it was bypassed. I am continuing to read up on Azure Functions.

Thanks again.

**Comment by AndrewTriesToCode** [comment]
Hi again and thanks again for this PR.

I'd love to include this soon. I noticed that it has some conflicts to be resolved. Do you still have interest in submitting this? My only request is that you remove the block starting at line 61 -- I explicitly do not want a strategy to act as authentication and set the `User` especially since it bypasses validation to prevent a chicken/egg problem when validation requires the tenant to be known.

**Comment by Valks** [comment]
I've removed the code and ran the tests which say they all pass (locally).

I had to add that code because the Principal wasn't been populated when I needed it. That said, for all I remember it could have been to do with the default authentication scheme issue which this pull requests addresses in which case it may no longer be a concern.

Let me know if you need me to do any further changes to this PR.

**Pull request merged**
