### PR TITLE
Items is not being updated correctly in TenantInfo constructor

### PR DESCRIPTION
**Pull request by chernihiv**
Items is not being updated correctly in TenantInfo constructor.

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
Thanks for submitting this fix. Is there any way you can clean up the commits to prevent all the changes in the .sln file? Also are you able to GPG sign your commit?

**Comment by chernihiv** [comment]
It's not a blocker, there are workarounds, e.g.

```
var tenantInfo = new TenantInfo("id", "identifier", "name", null, new Dictionary<string, object>());
tenantInfo.Items.Add("Key", "Value");
```
or 

```
public sealed class FixedTenantInfo
{
    public IDictionary<string, object> Items { get; set; } = new Dictionary<string, object>();
}
```
```
var tenantInfo = JsonConvert.DeserializeObject<TenantInfo>(cachedValue);
var fixedTenantInfo = JsonConvert.DeserializeObject<FixedTenantInfo>(cachedValue);
foreach (var item in fixedTenantInfo.Items)
{
    tenantInfo.Items.Add(item.Key, item.Value);
}
```

**Comment by chernihiv** [comment]
@achandlerwhite  Would it be better 'reset' changes remote or create new PR?
I've never done GPG and don't have secret key. 
Feel free to fix it yourself.

**Comment by AndrewTriesToCode** [comment]
I don’t think a revert will work because the originals will still not be
PGP signed—if you don’t want to sign just let let me know and I can turn
that off.

I could be wrong about that though.

**Comment by AndrewTriesToCode** [comment]
@chernihiv Hi I've thought about it and decided to remove the gpg signing requirement. I want to make sure you get credit for the fix. Can you resubmit a PR from a branch in your fork titled "feature/91-TenantInfo-ctor-fix"?

**Comment by chernihiv** [comment]
Hi @achandlerwhite , sorry for the delay.

It's my first contribution on github, therefore I'd like to clarify:
I forked repo, committed changes into master and created PR. 
Therefore, I have to create branch `feature/91-TenantInfo-ctor-fix` based on forked `master` branch, apply fix and submit PR into your `master`, right?

**Comment by AndrewTriesToCode** [comment]
@chernihiv No problem! Thanks for your contribution. Typically you would fork a project, then create a "feature" branch in your fork, then submit a pull request from your branch to the upstream project's master branch. We don't really need to worry about it--I'll accept this pull request as-is soon.

**Comment by chernihiv** [comment]
@achandlerwhite as far as I can see it was merged already. Let me know if I can help you.

**Comment by AndrewTriesToCode** [comment]
@chernihiv yeah I added a unit test and went ahead and pulled your change into master.

**Comment by AndrewTriesToCode** [comment]
Note: contents of this PR are no longer in the code as of release 6.

**Pull request merged**
