### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by brockallen**

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
Thanks for the typo fix. By the way I get a lot of requests on how to best integrate Finbuckle.MultiTenant with IdentityServer. I'd be interested in discussing ideas with you if you think it's worthwhile. My email is in my GitHub profile. Thanks again.

**Comment by brockallen** [comment]
> Thanks for the typo fix

No problem. There's some irony that I'm helping with a typo, but I saw it and after all the typo PRs I've accepted I thought I'd help out :)

>  By the way I get a lot of requests on how to best integrate Finbuckle.MultiTenant with IdentityServer.

Yea, that's exactly what I'm looking into now.

**Comment by AndrewTriesToCode** [comment]
I've submitted a PR for a typo in IS4 so I know what you mean. 

Check out issue #374 to see how far we got with multitenant IS4

**Pull request merged**
