### PR TITLE
Add Azure Functions Support (Tenant Attribute)

### PR DESCRIPTION
**Pull request by Valks**
Adds Azure functions support.

Adds a binding to get the Tenant.

Tasks remaining:
- [x] Samples
- [ ] Tests
- [ ] Documentation

To use:
In your startup setup your tenant provider as per normal.
```C#
builder.Services.AddMultiTenant<Organisation>()
                .WithCosmosDbStore(databaseName: "Database", collectionName: nameof(Organisation))
                .WithClaimStrategy("organisationId");
```

You don't need to call ```UseMultiTenant()```, it's already done as part of the binding startup.

Then in your HttpTrigger functions add: ```[Tenant] TenantInfo tenant,```
TenantInfo can be any class derived from ITenantInfo. The binding will map it accordingly.

This is a rebase from the develop branch. I haven't checked it yet to see if anything is broken vs what I've been using. But it does work, just might need a little TLC.

Also, the tests need to be finished.

Note:
- I'll do a separate pull request for the CosmosDB provider later.
- Samples haven't been tested.

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
@Valks thanks! I have a new release getting ready that will go out before we merge this but this will probably be included in the subsequent release.

**Comment by AndrewTriesToCode** [comment]
@Valks 
I'm simplifying the git repo and going with feature branches off the `main` branch going forward. I modified this PR to target main.

**Comment by Valks** [comment]
I'll just leave a note for the moment. Using the built in auth providers causes an exception. Up until now I've been using the Microsoft.Identity.Web package for Auth.

In ClaimStrategy.cs line 45: ```var handler = (IAuthenticationHandler)ActivatorUtilities.CreateInstance(httpContext.RequestServices, authScheme.HandlerType);``` it hits a null reference exception.

I'll take a look and see what can be done.

**Comment by AndrewTriesToCode** [comment]
@Valks the strategy uses the default authenticate scheme -- whatever it happens to be. I should probably add a way to have it use a specific scheme if requested

**Comment by Valks** [comment]
I was just about to create a pull request with the ClaimsStrategy done.

**Comment by Valks** [comment]
I have this feature working now (built in auth providers also work). I just need review what I've got to make sure I haven't missed anything important.

A note to anyone who might use this feature. At the moment because Azure Functions don't really have support for alternate Auth Providers you have to use reflection to reload their providers otherwise the built in Azure services will fail to authenticate. I have managed to get it working, see:

https://github.com/AzureAD/microsoft-identity-web/issues/916#issuecomment-785512851

**Comment by AndrewTriesToCode** [comment]
Bad Stalebot! I'm still planning to incorporate this. Sorry for the long wait!

**Comment by AndrewTriesToCode** [comment]
Taking a closer look now and wow this is really great. Appreciate the contribution! I don't know much about Azure functions myself so I will need a little time to work thought it all.

**Comment by AndrewTriesToCode** [comment]
I've been digging in and  I am impressed at your work with the custom binding implementation.

One question though-- `AddMultiTenant<T>` registers `T` and `ITenantInfo` in DI -- are these not simply available via parameter injection as shown [in the docs here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#use-injected-dependencies)?

I like the samples and the host helper functions. One thing I would want to test is if the per-tenant-options functionality works with this -- I don't see why it wouldn't but would want to be sure.

**Comment by Valks** [comment]
Are you referring to the need to use the Attribute ```[Tenant]```? The attribute is required so that it runs the bindings pipeline to populate the TenantInfo.

If you didn't want to use the attribute bindings you could pull in the services via DI and then manually do it as part of the function but that's not the model users of Azure Functions expect and the bindings (should) ensure that the TenantInfo is populated correctly.

**Comment by AndrewTriesToCode** [comment]
I see what you are saying about the binding approach and user expectations.

I was thinking that the DI wouldn't even need to bring in "services" that users need to use to get th tenant info-- just injecting `TenantInfo` itself (or the custom tenant info class) should work in theory since it is registered by the library. It might work, but it's nice to have the binding too.

Any thoughts on per-tenant options working as expected? Unfortunately I can't test this easily because I foolishly installed the beta MacOS and the Azure Functions dev tools haven't quite caught up...

**Comment by Valks** [comment]
So, in following up on all the pull requests (I should have put more time into this when I did them).

With Azure Functions moving to an out of process model which supports middleware it is probably best to remove .net core 3.1 support. This is because I used reflection to register the necessary middleware in 3.1 which isn't officially supported:
[src/Finbuckle.MultiTenant.AzureFunctions/Host/Middleware/FunctionsHttpMiddlewareExtensions.cs](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/99c65431aa2fa4200b81d5e542610850f30bba18/src/Finbuckle.MultiTenant.AzureFunctions/Host/Middleware/FunctionsHttpMiddlewareExtensions.cs)

The other benefit of the out of process model is it will probably work with the default implementation, that way the only changes needed will be to add the binding providers.

**Comment by AndrewTriesToCode** [comment]
@Valks Hello sir and apologize again for taking so long.

I have updated the contribution guidelines and want to see if you would agree that this functionality might make more since to host on your own repo and to link to it in the Finbuckle docs? I see that as a good middle ground for new features that are a little outside the guidelines of prioritizing prioritizes maintainability, core functionality, and common use-cases.

Your work here is impressive so please don't take this as a rejection.

**Comment by Valks** [comment]
I agree that with the direction of Azure Functions this code shouldn't make its way into this repo (the middleware hacks shouldn't be needed anymore in current Azure Functions versions). Totally not offended in any way and agree with the guidelines.

As I think about it now, probably a subset to enable the attribute to get TenantInfo and the extension method to wire it all up would be a good fit. They shouldn't add much in the way of maintenance and maintainability.

I can look at having this version in my repo and anyone is welcome to use it as-is.

**Comment by AndrewTriesToCode** [comment]
> I agree that with the direction of Azure Functions this code shouldn't make its way into this repo (the middleware hacks shouldn't be needed anymore in current Azure Functions versions). Totally not offended in any way and agree with the guidelines.
> 
> As I think about it now, probably a subset to enable the attribute to get TenantInfo and the extension method to wire it all up would be a good fit. They shouldn't add much in the way of maintenance and maintainability.
> 
> I can look at having this version in my repo and anyone is welcome to use it as-is.

Ok, I'll close it out and if you have a good working solution for this I'd be happy to link to it in the docs.

**Pull request closed without merging**
