### PR TITLE
Added events system

### PR DESCRIPTION
**Pull request by natelaff**
- Added events system.

Usage:

```lang csharp
services.AddMultiTenant<TenantInfo>(config =>
                {         
                    config.Events = new MultiTenantEvents()
                    {
                        OnTenantResolved = async (context) =>
                        {
                            ITenantInfo tenant = context.TenantInfo;
                            // do something with found tenant here...
                            await Task.FromResult(0);
                        },
                        OnTenantNotResolved = async (context) =>
                        {
                            if (context.Context is HttpContext httpContext)
                            {
                                // return status code, redirect, etc...
                                httpContext.Response.StatusCode = 404;
                                await Task.FromResult(0);
                            }
                        }
                    };
                })
```

- AuthenticationService no longer challenges when tenant is null.

### CODE REVIEW

**Comment by natelaff** [comment]
I thought I'd touch base on the AuthenticationService change since this goes hand in hand with this premise of gracefully handling when a tenant is not found.

Since this service is only registered when using WithPerTenantAuthentication() it didn't seem critical to challenge if the tenant is not found. It was my belief that in fact if a tenant is not found when using per tenant authentication it should not occur and caused more problems by doing so.

This fixed my issues in #349 

That said, if retaining past behavior here is critical, adding a MultiTenantAuthenticationOptions that alters this behavior could be added.

i.e.
```csharp
services.AddMultiTenant<TenantInfo>()
                .WithPerTenantAuthentication(authOptions => {
                    authOptions.ChallengeOidcIfTenantNotResolved = false;
                })
```
Not sure how necessary this is, you know how people use this library better than I do :) I just know this was a critical fix for my scenario.

**Comment by AndrewTriesToCode** [comment]
Hi @natelaff
The events look good, thanks for thinking it through. A few thoughts:

- I'd prefer the `AuthenticationService` change to be opt-in because some users use a shared login approach and the challenge needs to redirect to the login page before the tenant is known. For openId connect you are probably right but I have to keep other types of challenges in mind.

- Did you intend to include the changes in `MultiTenantBuilderExtensions` with the token replacement in OpenID Connect options? Can you tell me what your use case is here? In the cookies they are paths but for OpenId Connect I'm not seeing the purpose except maybe for authority. I'm not against the idea though. If we include this we need to add it to the description.

- Any thoughts on tests for the events?

**Comment by natelaff** [comment]
@AndrewTriesToCode cool, i can make this option for the challenge.

Yes, those changes were intended as a quick one. The authority was the main use case, but figured you could also customize clients (i.e. it's theoretical each tenant could have a separate client).

Testing... I have no idea. I tried to stub it out. I have been a solo developer for like 14 years. unit testing is not something i'm super proficient at hahaha

**Comment by natelaff** [comment]
#364 is changed in this

**Comment by AndrewTriesToCode** [comment]
Thanks @natelaff

I plan to add some unit tests/updated docs around these updates.

**Pull request merged**
